### ISSUE TITLE
remove dependency on @pie-ui/placement-ordering from @pie-element/match

### ISSUE THREAD

**Issue by edeustace** [pie-framework/pie-elements#103]
remove: https://github.com/pie-framework/pie-elements/blob/develop/packages/match/configure/src/answer-config-block.jsx#L11

If swap is to be shared - it should be in a `@pie-lib/*` package - whichever is appropriate.

**Comment by lakatosandrei** [comment]
Fixed by [this](https://github.com/pie-framework/pie-elements/pull/104)
