### ISSUE TITLE
Categorize: Text overlapping in settings

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#30]
"Remove all tiles after placing" and "Shuffle" text is overlapping. @edeustace 

<img width="223" alt="screen shot 2018-06-26 at 2 56 45 pm" src="https://user-images.githubusercontent.com/36770983/41934347-7ce728b6-7954-11e8-9d01-8280e85a6240.png">

**Comment by elodszopos** [comment]
This has been taken care of. Please let us know if the latest version still has the issue @alex-alberto.

**Comment by alex-alberto** [comment]
@elodszopos looks good, thanks!
