### ISSUE TITLE
MC question feedback and correct answer are not getting bound to PIE view

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#33]
While editing Multiple Choice question feedback and correct answer are not getting bound to PIE view. 1st image is while create, 2nd is while edit.

![image003](https://user-images.githubusercontent.com/36770983/42453315-5fe3424e-835a-11e8-9d39-733bd062f75d.jpg)

![image005](https://user-images.githubusercontent.com/36770983/42453323-676832e0-835a-11e8-8805-741ef881ccad.jpg)

@edeustace

**Comment by evaneus** [comment]
if you can give us some config code samples that show how the config model is not being applied to correctly to the config view that will help us look at this issue. thx.

**Comment by narayankj** [comment]
In "pie-controllers.js", if we add commented code in below method it works.. 
const prepareChoice = (mode, defaultFeedback) => choice => {

  const out = {
    label: choice.label,
    value: choice.value
  };

  if (mode == 'evaluate') {
    out.correct = !!choice.correct;

    const feedbackType = choice.feedback && choice.feedback.type || 'none';

    if (feedbackType === 'default') {
      out.feedback = defaultFeedback[choice.correct ? 'correct' : 'incorrect'];
    } else if (feedbackType === 'custom') {
      out.feedback = choice.feedback.value;
    }
  }
  //else if (mode == 'gather') {
  //    out.correct = !!choice.correct;

  //    const feedbackType = choice.feedback && choice.feedback.type || 'none';

  //    if (feedbackType === 'default') {
  //        out.feedback = defaultFeedback[choice.correct ? 'correct' : 'incorrect'];
  //    } else if (feedbackType === 'custom') {
  //        out.feedback = choice.feedback;
  //    }
  //}

  return out;
};
