### ISSUE TITLE
[MC] Existing PMLC math equations won’t show up in PIE editor

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#46]
Math equations for existing PowerMyLearning Connect questions won’t show up in PIE editor. This used to work before the fractions fix in the math editor. Please let us know if we need to fix/modify something from our end
http://sbox.powermylearning.org/piedemo/MultipleChoice_Math_Example.html
https://github.com/paritoshcardinal/pie_elements_demo/blob/master/mc/math.json

![image008-2](https://user-images.githubusercontent.com/36770983/43536035-94c0110e-9589-11e8-8bcd-419a39b5db21.jpg)

@edeustace @elodszopos @narayankj

**Comment by edeustace** [comment]
@narayankj - is this a blocker for you, or can you work with `\(...\)` for now? If it's not a blocker I'll add support for `$...$` as a new issue.

**Comment by narayankj** [comment]
@edeustace It's not a blocker, though our existing questions has equations with` $..$`

**Comment by edeustace** [comment]
Closed - see #55
