### ISSUE TITLE
Cannot enter value for fractions

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#47]
Cursor won’t stay in place to enter value for fractions, when we type something it appears next to fraction.

![image009](https://user-images.githubusercontent.com/36770983/43536169-ed2b03a8-9589-11e8-9474-28ea7887699b.png)

@edeustace @elodszopos @narayankj

**Comment by edeustace** [comment]
Fixed in: `@pie-lib/editable-html@6.2.4`
