### ISSUE TITLE
Tables in existing PMLC questions migrated to PIE don't show in the PIE editor

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#48]
Tables in existing PMLC questions migrated to PIE don't show in the PIE editor, thought it renders in the preview section (on the right).
http://sbox.powermylearning.org/piedemo/MultipleChoice_Table_Example.html
https://github.com/paritoshcardinal/pie_elements_demo/blob/master/mc/table.json

![image010](https://user-images.githubusercontent.com/36770983/43536366-6d90684e-958a-11e8-9bb0-59c991d2ab8f.jpg)

@edeustace @elodszopos @narayankj

**Comment by elodszopos** [comment]
@edeustace Once again, I looked into this and I can confirm that the serialization logic is stripping off the table related tags for some reason. The `markup` prop contains the correct value but upon serializing and parsing back into usable format, the tags disappear.

Relevant lines of code are in the editable-html constructor, src/index.js, around lines 25-35.

**Comment by edeustace** [comment]
@narayankj, this relates to slatejs core schema rules. We'd have to update the schema.

**Comment by edeustace** [comment]
There is a plugin for table support will check it out.

**Comment by edeustace** [comment]
I have begun to add support for this - note that full table editing support may have to be pushed out to another issue and for now we set up table rendering.

**Comment by alex-alberto** [comment]
Closing since partial support has been released.
