### ISSUE TITLE
[P3] Cursor appears in wrong section when editing Multiple Choice item choices in Firefox

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#49]
Steps to reproduce:
1. In Firefox, Copy around 5 lines of text
2. Paste in the prompt section
3. Click on Choice Edit field to enter text

Expected result: The cursor appears in the selected choice section
Actual result: The cursor appears in the prompt section

Can be reproduced here: http://sbox.powermylearning.org/piedemo/MultipleChoice_Example.html

**Comment by edeustace** [comment]
@alex-alberto can you provide a url that we can run/reproduce the issue?

**Comment by hussham-khan** [comment]
@edeustace you can use this URL in firefox to reproduce this issue:
http://sbox.powermylearning.org/piedemo/MultipleChoice_Example.html

**Comment by alex-alberto** [comment]
@edeustace we are no longer able to reproduce this issue. I know you said via email that you haven't looked into it, so I'm not sure what happened, but closing now.

**Comment by PowerMyLearningConnect** [comment]
@edeustace 
i am closing this, since user has to save prompt before moving onto the next field.
