### ISSUE TITLE
[Categorize] Choosing "below" option for label throws error

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#50]
Click on Label Position and choose Below option, We will get below issue-
![ebahdoilnhcoeiml](https://user-images.githubusercontent.com/36770983/43536869-bb4ea4f0-958b-11e8-9353-ba4d6849c023.png)

Tested on http://sbox.powermylearning.org/piedemo/Category_Example.html

@edeustace @elodszopos @narayankj

**Comment by elodszopos** [comment]
Should be resolved if the PR merged above has been published.

**Comment by edeustace** [comment]
@alex-alberto fixed in `@pie-element/categorize@2.3.0` please re-test

**Comment by alex-alberto** [comment]
Thanks @edeustace, it works. Closing.
