### ISSUE TITLE
[Categorize] No maximum for choice per row

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#51]
Categories per row and Choices per row can be set more than 4 by directly entering the number and after that we get below issue-
![pkhadoaaojciloid](https://user-images.githubusercontent.com/36770983/43536969-0270fc48-958c-11e8-996e-d44dcad0a6fa.png)

Tested on http://sbox.powermylearning.org/piedemo/Category_Example.html

@edeustace @elodszopos @narayankj

**Comment by elodszopos** [comment]
Should be resolved if the above PR that was merged has been published.

**Comment by edeustace** [comment]
@alex-alberto released in `@pie-element/categorize@2.3.0` please re-test.
