### ISSUE TITLE
[Categorize] Math editor doesn't display properly

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#53]
When Editing/Adding a choice label, and trying to add a math equation, the math editor doesn't properly show up.

![ijceblidiknkipbd](https://user-images.githubusercontent.com/36770983/43537298-efdeeed6-958c-11e8-9fd6-44e99cd824ea.png)

Tested on http://sbox.powermylearning.org/piedemo/Category_Example.html

@edeustace @elodszopos @narayankj

**Comment by elodszopos** [comment]
Duplicate of #52
