### ISSUE TITLE
editable-html - support latex $ symbol

### ISSUE THREAD

**Issue by edeustace** [pie-framework/pie-elements#55]
A math node should support `<span data-latex="">$1+2=3$</span>`.

See:

![latex](https://user-images.githubusercontent.com/3695519/43546722-69ba7382-95a7-11e8-8b19-26a8c64f669c.png)

**Comment by narayankj** [comment]
@edeustace We tried removing $...$ from our equations, which results in not showing certain equations. For example, in below image 4 doesn't show up in equation editor $ removed from `$4$`.
I tried adding similar value from PIE editor (5), generated latex is`$5$` 

![image](https://user-images.githubusercontent.com/3695519/43608399-01781d7e-966f-11e8-8cb6-4eebde2340b4.png)

**Comment by edeustace** [comment]
Can you have a look at this preview of the fix: https://out-dsiglrxdpn.now.sh/pie-lib/editable-html/

Note that only `$..$` and `\(..\)` are supported, because the other wrappers require changing the layout nature of the math.

**Comment by alex-alberto** [comment]
@edeustace this looks good!
