### ISSUE TITLE
[Categorize] Math equations don't render

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#57]
When adding equation, it's showing correctly in authoring section, but not showing in rendering section. See below.

![image005-2](https://user-images.githubusercontent.com/36770983/43793310-2453685c-9a49-11e8-8346-1b1e49515e0f.png)

Tested at: https://sbox.powermylearning.org/piedemo/Category_Example.html.

@edeustace @elodszopos @narayankg

**Comment by edeustace** [comment]
@elodszopos you free to look into this? I'm guessing it's missing katex + the call to render in the `ReactDOM.render` callback.

**Comment by elodszopos** [comment]
PR has been opened with the fix @ https://github.com/pie-framework/pie-ui/pull/20

**Comment by edeustace** [comment]
fixed in: @pie-ui/categorize@0.4.0
