### ISSUE TITLE
Tables render with no borders

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#58]
Tables have borders on editing side, but none on rendering. This applies to new tables created in the editor, and tables in imported CoreSpring items.

<img width="1438" alt="screen shot 2018-08-10 at 3 00 16 pm" src="https://user-images.githubusercontent.com/36770983/43976383-6204ce22-9cae-11e8-8e18-531ceff9d190.png">

Tested at: http://sbox.powermylearning.org/piedemo/MultipleChoice_Edit_Example.html

**Comment by edeustace** [comment]
We'll have to add border control to the toolbar - maybe toggle it on/off.

**Comment by alex-alberto** [comment]
@edeustace yes, that should do it. Are you looking into it today? Thanks!

**Comment by edeustace** [comment]
@alex-alberto - can you send me a sample of a corespring table markup that I can check? I'm adding a toggle border button atm.

**Comment by edeustace** [comment]
@alex-alberto - you can see the border support here: https://out-jokyqakwpq.now.sh/pie-lib/editable-html/

**Comment by narayankj** [comment]
**Table** 
`<table cellspacing="0" cellpadding="4" class="borderall">  <tbody> <tr>   <td style="width:140px" class="center bold">Trial</td>   <td style="width:140px" class="center bold">Mass NH<sub>3</sub></td>  <td style="width:140px" class="center bold">Mass HCl</td>  <td style="width:140px" class="center bold">Mass NH<sub>4</sub>Cl</td>  </tr>   <tr>  <td class="center">1</td>  <td class="center">3.40 g</td>  <td class="center">7.30 g</td>   <td class="center\">10.70 g</td>  </tr>   <tr>  <td class="center">2</td>   <td class="center">?</td>   <td class="center">?</td>   <td class="center">32.10 g</td> </tr>  </tbody></table>`

**Prompt from corespring as is**

`"prompt": "<div id=\"CALCULATOR\" corespring-calculator=\"\"></div><br /><div class=\"para\">Different amounts of ammonia gas (NH<sub>3</sub>) and hydrogen chloride gas (HCl) are combined in the laboratory. Some of the masses of the reactants and the products for two trials are shown below.</div> \n<div stsyle=\"width:640px\" class=\"para center bold\">Experimental Masses of Ammonia and Hydrogen Chloride</div> \n<table cellspacing=\"0\" cellpadding=\"4\" class=\"borderall\"> \n <tbody>\n  <tr>\n   <td style=\"width:140px\" class=\"center bold\">Trial</td>\n   <td style=\"width:140px\" class=\"center bold\">Mass NH<sub>3</sub></td>\n   <td style=\"width:140px\" class=\"center bold\">Mass HCl</td>\n   <td style=\"width:140px\" class=\"center bold\">Mass NH<sub>4</sub>Cl</td>\n  </tr> \n  <tr>\n   <td class=\"center\">1</td>\n   <td class=\"center\">3.40 g</td>\n   <td class=\"center\">7.30 g</td>\n   <td class=\"center\">10.70 g</td>\n  </tr> \n  <tr>\n   <td class=\"center\">2</td>\n   <td class=\"center\">?</td>\n   <td class=\"center\">?</td>\n   <td class=\"center\">32.10 g</td>\n  </tr> \n </tbody>\n</table> \n<div class=\"para\">Based on the law of constant composition, which of the following values correctly replace the question marks in the table?</div><div id=\"5758\" corespring-multiple-choice=\"\"></div>",`

**Comment by narayankj** [comment]
This is how it looks
![image](https://user-images.githubusercontent.com/3695519/44222498-b0c6aa00-a152-11e8-9be6-ab17464398c5.png)

**Comment by edeustace** [comment]
@narayankj @alex-alberto - can you try the following: https://out-pjyxvlhruf.now.sh/editable-html

**Comment by narayankj** [comment]
@edeustace I still dont see borders.

![image](https://user-images.githubusercontent.com/3695519/44229160-2dfb1a80-a165-11e8-95eb-f1c8f4b0375c.png)

**Comment by edeustace** [comment]
You need to toggle it on/off in the toolbar. See the rightmost button.

**Comment by narayankj** [comment]
@edeustace  Thank you, I see border when toggled. Does it mean users has to edit, toggle and save for table rendering once this fix is released?

**Comment by edeustace** [comment]
if the incoming table has a border it'll be rendered with that border and the output will have it too.

**Comment by narayankj** [comment]
Ok. Thanks.

**Comment by edeustace** [comment]
shall i release?

**Comment by edeustace** [comment]
fixed in: @pie-lib/editable-html@6.6.0

**Comment by narayankj** [comment]
@edeustace It looks good. Thanks
