### ISSUE TITLE
[P1] When creating a categorize question, browser does not scroll when dragging choices on categories

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#59]
Can be reproduced here: https://pie-catalog-demo.herokuapp.com/element/@pie-element/categorize

Steps to reproduce:
1. Create a few categories and choices, so that when you scroll at the bottom of the page to see the last choice, you cannot see all categories.
2. Try dragging a choice to a category that is not visible on the screen.

Expected: Browser scrolls to allow user to drop the choice on the desired category.
Actual: Browser does not scroll, making it impossible for the user to add a choice to a category that is not visible on the screen.

See the attached gif for examples. 
![categories-01](https://user-images.githubusercontent.com/36770983/44049083-1f35321c-9f01-11e8-9d89-c8ac0f0f1976.gif)

**Comment by alex-alberto** [comment]
@edeustace this is not a blocker to our release, but I think it should be high priority for usability when you have some time.

**Comment by lakatosandrei** [comment]
@PowerMyLearningConnect 
This issue can be reproduced but it seems like it works if you place the mouse near the end of the page (at least on my environment,  I'm using a Mac with a macOS Sierra Operating System):

http://www.giphy.com/gifs/EBuQ5QEF2LNcVsGLBG

As you can see, it works when scrolling the page up or down.

**Comment by PowerMyLearningConnect** [comment]
@lakatosandrei 
We haven't heard any other negative feedback from staff/users on this, so i think people have figured out where to place the cursor.
I am ok with this issue being closed.
