### ISSUE TITLE
Inline-choice - Feedback not displaying in evaluate mode

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#6]
After I selected an option, I get a checkmark or an X, but the feedback text entered does not show up.
<img width="1423" alt="screen shot 2018-03-28 at 3 15 53 pm" src="https://user-images.githubusercontent.com/36770983/38051912-a71386dc-329d-11e8-9177-09f3f8a3e2b8.png">

**Comment by edeustace** [comment]
@alex-alberto - the feedback is in a popover - if you click the x icon you'll see it. This is the same as how the corespring component works.

**Comment by alex-alberto** [comment]
@edeustace ah! sorry about the confusion. This can be closed then.
