### ISSUE TITLE
Text and images 3 levels down don't show up in editor in imported CoreSpring items

### ISSUE THREAD

**Issue by alex-alberto** [pie-framework/pie-elements#61]
Also, Images in questions imported from CoreSpring are not showing up. I have updated prompt and choice labels in demo app same from CoreSpring question.
               
1.  `<div><div><img` `src="aaa.jpg"/></div></div>`
http://sbox.powermylearning.org/piedemo/MultipleChoice_Image_Example.html

2. `<div` class=\"item-body\">\n       \n       \n        \n            <div class=\"para prompt\">Which of the following is a number where the digit 2 represents  the value of the digit 2 in the number 1,947.5286?</div>\n            \n            \n            \n            \n        <div id=\"RESPONSE\" corespring-multiple-choice=\"\"></div>\n    `</div>`

https://github.com/paritoshcardinal/pie_elements_demo/blob/master/mc/image.json

**Comment by edeustace** [comment]
From: https://github.com/paritoshcardinal/pie_elements_demo/blob/master/mc/image.json

```javascript
{
 //..

"prompt": "<div><div><div>Which table highlights doubles?</div>​<div id=\"0\" corespring-multiple-choice=\"\"></div>​<div><br /></div></div></div>",
//...
```
This prompt has a `div` that references a legacy corespring component. There's a couple of issues with that: 
  1. a prompt for an element should *never* try and render another pie element within it
  1. this reference is using the old corespring syntax - this will never work anywhere in pie

I'm trying to repro your other issue now

**Comment by edeustace** [comment]
I tried both of the samples above - the image renders and so does the text. As mentioned trying to get a component to render within the prompt will never work and you shouldn't be doing it. Can you provide me with another example of it not working?

**Comment by narayankj** [comment]
@edeustace You mean removing `<div id=\"0\" corespring-multiple-choice=\"\"></div>​` will work.

**Comment by narayankj** [comment]
@edeustace is there any update on this fix? This fix will make more then 50% of imported questions work in PIE editor.

**Comment by alex-alberto** [comment]
@edeustace @elodszopos any update on this fix? Thanks!

**Comment by edeustace** [comment]
I can repro the issue of `<div><div><img/></div></div>` investigating

**Comment by narayankj** [comment]
@edeustace its not only image anything with grand parent wont show up 
`<div><div><span> some text </span></div></div>`
or
`<div><span><p> some text or image or math </p></span></div>`

**Comment by edeustace** [comment]
Cheers, will keep that in mind.

**Comment by edeustace** [comment]
@narayankj @alex-alberto - can you try this build: https://out-iropundxmv.now.sh/editable-html/

**Comment by narayankj** [comment]
@edeustace it looks good. Thanks :)

**Comment by edeustace** [comment]
fixed in @pie-lib/editable-html (6.6.3)

**Comment by narayankj** [comment]
@edeustace  Fix doesn't work in many cases ex: check for image in prompt,

https://github.com/paritoshcardinal/pie_elements_demo/blob/master/mc/image.json
http://sbox.powermylearning.org/piedemo/MultipleChoice_Image_Example.html

@alex-alberto could you reopen the issue please?

**Comment by edeustace** [comment]
I just tried with the markup from the json above - and it worked on the demo site: https://out-iropundxmv.now.sh/editable-html/.
<img width="1198" alt="screen shot 2018-08-30 at 21 46 31" src="https://user-images.githubusercontent.com/101623/44878223-393e6200-ac9e-11e8-8b76-27558af77d2f.png">

Could you double check your build and make sure that you have the latest of @pie-lib/editable-html?

**Comment by narayankj** [comment]
@edeustace  Please look for prompt. which has `<div>Which is greater, 0.2 or 0.03? Use the number line below to help you.<div style=\"text-align: left;\"><img  src=\"http://qa-media.powermylearning.org/content/assets/userpromptimages/1b7730d6-f945-4cb1-9925-0e1ab6a6b6f3_1534792362356-Screen%20Shot%202018-08-20%20at%203.06.17%20PM.png\"></div>​​<div></div></div>`

**Comment by edeustace** [comment]
got it thanks - will check

**Comment by edeustace** [comment]
This is happening because the node is mixing inline/text and block - so the block gets removed. https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/schema.js#L35
Will need to apply a custom normalization for this.

**Comment by alex-alberto** [comment]
@edeustace per @narayankj's last comment, this issue hasn't been fully resolved. I don't have the ability to reopen it, would you be able to, just so we can see it in the list of open issues and keep track of it? Thank you!

**Comment by narayankj** [comment]
> This is happening because the node is mixing inline/text and block - so the block gets removed. https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/schema.js#L35
> Will need to apply a custom normalization for this.

@edeustace is this fixed in latest version?
