### ISSUE TITLE
latex displaystyle in text editor?

### ISSUE THREAD

**Issue by edeustace** [pie-framework/pie-elements#64]
<span data-latex="">\(\displaystyle - \frac{36}{55}\)</span>

 

Above latex doesn’t renders but doesn’t show up in PIE editor. I tested it with  

https://out-pjyxvlhruf.now.sh/editable-html as well and see same issue. Lot of CoreSpring questions have latex like this.

This might be related: https://github.com/mathquill/mathquill/issues/589

**Comment by edeustace** [comment]
This is definitely a mathquill issue. @narayankj - is this flag something you can easily remove? If not we'll just have to strip it if present internally in the math plugin and log a warning.

**Comment by narayankj** [comment]
@edeustace we can, but we have already got CoreSpring questions in production and we cannot run again with this fix.

**Comment by edeustace** [comment]
fixed in: @pie-lib/editable-html@6.6.2
