### ISSUE TITLE
PIE editor doesn't recognize <ul>,  <li> tags

### ISSUE THREAD

**Issue by narayankj** [pie-framework/pie-elements#66]
![image](https://user-images.githubusercontent.com/3695519/44533796-4ec2f300-a6c4-11e8-9f64-7e3bdb6ae0f5.png)

**Comment by edeustace** [comment]
@narayankj - can you send source code or a link to some?

**Comment by narayankj** [comment]
@edeustace 

Demo: http://sbox.powermylearning.org/piedemo/MultipleChoice_Format_Issue_Example.html
config: https://github.com/paritoshcardinal/pie_elements_demo/blob/master/mc/format.json
