### ISSUE TITLE
Uncaught Error: A schema rule could not be normalized after sufficient iteration

### ISSUE THREAD

**Issue by narayankj** [pie-framework/pie-elements#69]
http://sbox.powermylearning.org/piedemo/MultipleChoice_Math_Example.html
https://github.com/paritoshcardinal/pie_elements_demo/blob/master/mc/math.json

![image](https://user-images.githubusercontent.com/3695519/44731942-4f87ca80-aab2-11e8-89c4-8b981f0b294d.png)

**Comment by lakatosandrei** [comment]
@narayankj 
Can't reproduce this anymore

**Comment by narayankj** [comment]
@lakatosandrei Even I cannot, now. Looks like latest PIE fixed it. Closing it. Thanks,
