### ISSUE TITLE
[P1] In a Multiple Choice prompt, users cannot type to the left of an uploaded image

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#70]
Steps to reproduce:

1. Insert an image in a Multiple Choice prompt field, and save.
2. Click into the prompt field again to edit, and try to place cursor to the left of the image to type.

Expected behavior: user is able to add text to the left of the image.
Actual behavior: user is not able to type anything to the left of the image.

As a workaround, users have to trash the image, type the text, and reinsert the image.

This can be reproduced here: https://pie-catalog-demo.herokuapp.com/element/@pie-element/multiple-choice

**Comment by evaneus** [comment]
This is valid, but needs some feature and design decisions. We could add (to the control bar that lets you resize the image) some extra controls that control text/alignment behaviour. 

Possible Approach:

Add icons to the image toolbar with the following actions:

Align Left - align the image to the left and text wraps (left aligned in its own div) to the right
Align Right - align the image to right and text wraps to the left 
Center - align the image to the center and do not wrap text
No Alignment - align the image to the left and do not wrap text

Note: there are no material icons that are perfect for this, the icons avail for alignment indicate text. We could use these for near term, but would be more ideal to have more specific icons:

https://material.io/tools/icons/?search=align&style=baseline

**Comment by PowerMyLearningConnect** [comment]
@edeustace 
Not sure if the proposed functionality will work. 
If users enter an image, and want to place text before it, would they have to "Align Right" and then enter text? And then if they don't want it right aligned after they place a return, they have to click left align?

If we can't get the cursor to appear to the left of the image, I wonder if a less elegant solution is to  always insert a return above/before an image so that the cursor can be available above the image to start typing text.

**Comment by lakatosandrei** [comment]
@PowerMyLearningConnect 

This should be fixed in the latest version.
