### ISSUE TITLE
[P2, need to add sandbox link] Increase default cell size when inserting a new table

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#71]
This is applicable to all items types where the table tool is enabled in the tool bar (currently in Multiple Choice prompts, but not available on pie demo site).

In a multiple choice prompt field, click on the table icon to open the table tools, then click on the new table button.

The default cell size is so small that it makes it hard to place the cursor in to type something. Increasing default cell size would improve UX.

<img width="759" alt="screen shot 2018-09-04 at 10 53 20 am" src="https://user-images.githubusercontent.com/36770983/45039224-22e32e00-b031-11e8-8eae-e272cb34e040.png">

**Comment by lakatosandrei** [comment]
@PowerMyLearningConnect 
This is going to be fixed after [this](https://github.com/pie-framework/pie-lib/pull/55) PR is merged.
