### ISSUE TITLE
[P2] Add additional symbols into Math Editor

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#72]
The following symbols added to the Math editor would help support more Math equations. This applies to the text toolbar across all item types. Teachers feels like the math editor is not fully usable, since it does not allow them to create math item types requiring those symbols.

![image 28](https://user-images.githubusercontent.com/36770983/45039629-fa0f6880-b031-11e8-8a41-851aed0bebc4.png)

MATH FUNCTIONALITY CAN BE ACCESSED HERE:
1- Navigate to www.powermylearning.org
2- In top right corner, click on login, and enter the following credentials: user name: pie@gmail.com password: pieqa1
3- Navigate to the Questions page (within the Library section in the top nav).
4- Click on the New Question button in the top right corner.
5- Select Multiple Choice
6- In the prompt field, click on the insert Math icon.

**Comment by lakatosandrei** [comment]
@PowerMyLearningConnect 
Symbols should be in the latest version.
