### ISSUE TITLE
[Enhancement] Add ability to insert images into tables

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#73]
Enhancement: Adding an insert image button to the table tool bar to allow users to insert images inside tables. Applicable to all item types supporting tables (currently only Multiple Choice).

TABLE FUNCTIONALITY CAN BE ACCESSED HERE:
1- Navigate to www.powermylearning.org
2- In top right corner, click on login, and enter the following credentials: user name: pie@gmail.com password: pieqa1
3- Navigate to the Questions page (within the Library section in the top nav).
4- Click on the New Question button in the top right corner.
5- Select Multiple Choice
6- In the prompt field, click on the table icon.

<img width="758" alt="screen shot 2018-09-04 at 1 11 23 pm" src="https://user-images.githubusercontent.com/36770983/45046623-ace8c200-b044-11e8-90f9-984cea2e2f58.png">

**Comment by lakatosandrei** [comment]
Fixed by [this](https://github.com/pie-framework/pie-lib/pull/46)
