### ISSUE TITLE
[Enhancement] Add ability to insert Math equations into tables

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#74]
Enhancement: add ability to insert Math equations into tables. Applicable to all item types supporting tables (currently only Multiple Choice).

Currently, Math equations can only be added outside of a table. They can be added to a table via copy/paste as a workaround, but not all users realize that.

TABLE FUNCTIONALITY CAN BE ACCESSED HERE:
1- Navigate to www.powermylearning.org
2- In top right corner, click on login, and enter the following credentials: user name: pie@gmail.com password: pieqa1
3- Navigate to the Questions page (within the Library section in the top nav).
4- Click on the New Question button in the top right corner.
5- Select Multiple Choice
6- In the prompt field, click on the table icon.

<img width="758" alt="screen shot 2018-09-04 at 1 11 23 pm" src="https://user-images.githubusercontent.com/36770983/45047125-2af99880-b046-11e8-8012-8440d6147bd3.png">

**Comment by lakatosandrei** [comment]
Fixed by [this](https://github.com/pie-framework/pie-lib/pull/46)
