### ISSUE TITLE
[P1] User can only edit fields if cursor is placed at the very end of the text (Safari/Firefox)

### ISSUE THREAD

**Issue by PowerMyLearningConnect** [pie-framework/pie-elements#79]
Occurs in Safari and Firefox, for all item types.

Steps to reproduce:
1- In Safari or Firefox, try to click in the middle of any editable field that already has some text saved. The toolbar flickers (appears for a second and then disappears.
2- Click a the end of the text entered in the editable field. The toolbar appears and user can type/edit text.

See screencast: https://drive.google.com/file/d/1uG3kKuGRLO8d-XHAlDH4cz9dkgbuvPvM/view?usp=sharing

Can be reproduced on the pie demo site for all items.

Example Categorize here: https://pie-catalog-demo.herokuapp.com/element/@pie-element/categorize

Example Multiple Choice here: https://pie-catalog-demo.herokuapp.com/element/@pie-element/multiple-choice

**Comment by lakatosandrei** [comment]
@PowerMyLearningConnect 
I created a PR in the `slate-react` repo and now we're waiting for the review:
https://github.com/ianstormtaylor/slate/pull/2236

**Comment by lakatosandrei** [comment]
Fixed by [this](https://github.com/pie-framework/pie-lib/pull/44) pr locally and will be fixed after the slate pr is merged or another fix pops up.

**Comment by PowerMyLearningConnect** [comment]
@lakatosandrei 
I just tried testing this on Firefox on the PIE Demo site - 
For categorize, clicking into the field puts the cursor at the front of the pre-existing text...i cant move to a different spot by clicking, only by using cursor.
For MC, I can not make any edits to the text pre-populated in the fields now.

@edeustace

**Comment by lakatosandrei** [comment]
Like @edeustace said in another issue, the pie demo site is no longer maintained, so please try to use the latest version of the package and test locally.
